version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./dockerfile/server.dockerfile
    container_name: randomresourcegen-server
    ports:
      - 8084:8080
    env_file:
      - ./env/server.env
  client:
    build:
      context: .
      dockerfile: ./dockerfile/client.dockerfile
    container_name: randomresourcegen-client  
    env_file:
      - ./env/client.env


